#spring:
#  profiles.active: development
#
#---
#
#spring:
#  profiles: development
entity:
  name: Vasia
  lastName: @vjopy.ry
  age: 45
#
#---
#
#spring:
#  profiles: production
#entity:
#  name: RELIZICH
#  age: 666
#  lastName: @vjopy.ry2